[package]
name = "id_16_power_digit_sum"
version = "0.1.0"
authors = ["EdoardoLaGreca <lagrecaedoardo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.0"
