[package]
name = "id_15_lattice_paths"
version = "0.1.0"
authors = ["edoardo.lagreca"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
